//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public string CourseName { get; set; }
        public string LecturerName { get; set; }
        public string CourseId { get; set; }
        public System.DateTime MoedA { get; set; }
        public string ExamAClass { get; set; }
        public System.DateTime MoedB { get; set; }
        public string ExamBClass { get; set; }
        public string LectuerDay { get; set; }
        public string LectureStart { get; set; }
        public string LectureEnd { get; set; }
        public string Classroom { get; set; }
    }
}
